package com.growlink.cursos.domain;

public enum Categoria {
    INGENIERIA_SISTEMAS,
    INGENIERIA_CIVIL,
    INGENIERIA_INDUSTRIAL,
    INGENIERIA_ELECTRONICA,
    INGENIERIA_MECANICA,
    INGENIERIA_AMBIENTAL,
    MATEMATICAS,
    ADMINISTRACION_EMPRESAS,
    IDIOMAS,
    DERECHO
}
